name: Build and deploy Jekyll to Github Pages

on:
  push:
    branches:
      - blog

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
     # Create CNAME file that contains custom domain information
      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./devblog/CNAME"
          FILE_DATA: "devblog.pekspro.com"
       
     # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gemmms-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gemmms-

      - uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
